// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Teachly.DataAccess;

#nullable disable

namespace Teachly.DataAccess.Migrations
{
    [DbContext(typeof(TeachlyDbContext))]
    [Migration("20260507212734_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Teachly.DataAccess.Entities.InstitutionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.LessonPackageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PricePerLesson")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("PurchasedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("RemainingLessons")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalLessons")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("TutorSubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TutorSubjectId");

                    b.ToTable("LessonPackages", t =>
                        {
                            t.HasCheckConstraint("CK_LessonPackages_PricePerLesson", "\"PricePerLesson\" > 0");

                            t.HasCheckConstraint("CK_LessonPackages_RemainingLessons", "\"RemainingLessons\" >= 0");

                            t.HasCheckConstraint("CK_LessonPackages_RemainingLessons_Max", "\"RemainingLessons\" <= \"TotalLessons\"");

                            t.HasCheckConstraint("CK_LessonPackages_TotalLessons", "\"TotalLessons\" > 0");

                            t.HasCheckConstraint("CK_LessonPackages_TotalPrice", "\"TotalPrice\" > 0");

                            t.HasCheckConstraint("CK_LessonPackages_TotalPrice_Calculated", "\"TotalPrice\" = \"TotalLessons\" * \"PricePerLesson\"");
                        });
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.ReviewEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.HasIndex("StudentId", "TutorId")
                        .IsUnique();

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Reviews_Rating", "\"Rating\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.SolutionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TutorTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TutorTaskId");

                    b.ToTable("Solutions");
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.StudentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EducationLevel")
                        .HasColumnType("integer");

                    b.Property<Guid?>("InstitutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParentPhone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students", t =>
                        {
                            t.HasCheckConstraint("CK_Students_EducationLevel", "\"EducationLevel\" BETWEEN 1 AND 11");
                        });
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.SubjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.TutorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Tutors", t =>
                        {
                            t.HasCheckConstraint("CK_Tutors_AverageRating", "\"AverageRating\" BETWEEN 0 AND 5");

                            t.HasCheckConstraint("CK_Tutors_RatingCount", "\"RatingCount\" >= 0");
                        });
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.TutorFeedbackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GivenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Grade")
                        .HasColumnType("smallint");

                    b.Property<Guid>("SolutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TutorComment")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.HasKey("Id");

                    b.HasIndex("SolutionId")
                        .IsUnique();

                    b.ToTable("TutorFeedbacks", t =>
                        {
                            t.HasCheckConstraint("CK_TutorFeedbacks_Grade", "\"Grade\" BETWEEN 2 AND 5");
                        });
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.TutorSubjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("PricePerHour")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TutorId", "SubjectId")
                        .IsUnique();

                    b.ToTable("TutorSubjects", t =>
                        {
                            t.HasCheckConstraint("CK_TutorSubjects_PricePerHour", "\"PricePerHour\" > 0");
                        });
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.TutorTaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<Guid>("LessonPackageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LessonPackageId");

                    b.ToTable("TutorTasks");
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Age", "\"Age\" > 0");
                        });
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.LessonPackageEntity", b =>
                {
                    b.HasOne("Teachly.DataAccess.Entities.StudentEntity", "Student")
                        .WithMany("LessonPackages")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Teachly.DataAccess.Entities.TutorSubjectEntity", "TutorSubject")
                        .WithMany("LessonPackages")
                        .HasForeignKey("TutorSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("TutorSubject");
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.ReviewEntity", b =>
                {
                    b.HasOne("Teachly.DataAccess.Entities.StudentEntity", "Student")
                        .WithMany("Reviews")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Teachly.DataAccess.Entities.TutorEntity", "Tutor")
                        .WithMany("Reviews")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.SolutionEntity", b =>
                {
                    b.HasOne("Teachly.DataAccess.Entities.StudentEntity", "Student")
                        .WithMany("Solutions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Teachly.DataAccess.Entities.TutorTaskEntity", "TutorTask")
                        .WithMany("Solutions")
                        .HasForeignKey("TutorTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("TutorTask");
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.StudentEntity", b =>
                {
                    b.HasOne("Teachly.DataAccess.Entities.InstitutionEntity", "Institution")
                        .WithMany("Students")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Teachly.DataAccess.Entities.UserEntity", "User")
                        .WithOne("Student")
                        .HasForeignKey("Teachly.DataAccess.Entities.StudentEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.TutorEntity", b =>
                {
                    b.HasOne("Teachly.DataAccess.Entities.UserEntity", "User")
                        .WithOne("Tutor")
                        .HasForeignKey("Teachly.DataAccess.Entities.TutorEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.TutorFeedbackEntity", b =>
                {
                    b.HasOne("Teachly.DataAccess.Entities.SolutionEntity", "Solution")
                        .WithOne("TutorFeedback")
                        .HasForeignKey("Teachly.DataAccess.Entities.TutorFeedbackEntity", "SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.TutorSubjectEntity", b =>
                {
                    b.HasOne("Teachly.DataAccess.Entities.SubjectEntity", "Subject")
                        .WithMany("TutorSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Teachly.DataAccess.Entities.TutorEntity", "Tutor")
                        .WithMany("TutorSubjects")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.TutorTaskEntity", b =>
                {
                    b.HasOne("Teachly.DataAccess.Entities.LessonPackageEntity", "LessonPackage")
                        .WithMany("TutorTasks")
                        .HasForeignKey("LessonPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LessonPackage");
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.InstitutionEntity", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.LessonPackageEntity", b =>
                {
                    b.Navigation("TutorTasks");
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.SolutionEntity", b =>
                {
                    b.Navigation("TutorFeedback");
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.StudentEntity", b =>
                {
                    b.Navigation("LessonPackages");

                    b.Navigation("Reviews");

                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.SubjectEntity", b =>
                {
                    b.Navigation("TutorSubjects");
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.TutorEntity", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("TutorSubjects");
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.TutorSubjectEntity", b =>
                {
                    b.Navigation("LessonPackages");
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.TutorTaskEntity", b =>
                {
                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("Teachly.DataAccess.Entities.UserEntity", b =>
                {
                    b.Navigation("Student");

                    b.Navigation("Tutor");
                });
#pragma warning restore 612, 618
        }
    }
}
